Secure Stores (biometric / password)
focustree/starknet.dart pull request #128
Opened 2023-02-20 15:32 UTC by apalala-dev

This PR adds a `SecureStore` which can be implemented either with a `BiometricStore` or a `PasswordStore`.
It is used to store and retrieve the private key.

The `BiometricStore` is backed by [biometric_storage](https://pub.dev/packages/biometric_storage). For now, it is used only on Android.
iOS will use the Secure Enclave from an other [PR](https://github.com/gabsn/starknet.dart/pull/127).

When biometry is not available (Android without fingerprint enabled, Linux, Windows, Web, old Apple devices), the `PasswordStore` will be used instead.
This store uses AES 256 in GCM mode:
- The key is a SHA 256 hash of the password
- The IV is generated randomly and has a fixed size of 16 bytes. It can be overriden but must be 16 bytes long.
The IV and the cipher text are then concatenated and base64 encoded. They are finally stored in [shared_preferences](https://pub.dev/packages/shared_preferences).
Since the IV is always 16 bytes long, we can read it from the text stored in shared_preferences and use the provided password to decrypt the encrypted private key.

This should partially address #113 .

2023-02-21 08:10 UTC, ptisserand commented on packages/starknet_flutter/test/src/crypto/crypto_helper_test.dart
> +    // TODO the password must be 16 bytes long or it will fail
Password is not limited to 16 bytes, 16 bytes size is for initial vector.

2023-02-21 08:10 UTC, ptisserand commented on packages/starknet_flutter/lib/src/crypto/crypto_helper.dart
> +    required String cipherText,
I think using `cipherText` in `decrypt` is a bit confusing with `encrypt` documentation:
```
  /// Encrypt [plainText] with AES 256 GCM using [password] and [iv].
  /// The returned String is the base64 encoding of the IV and the cipher text.
  /// If [iv] is not provided, a random IV will be generated using [getIV].
  ```
Maybe rename it into `encodedCipherText`

2023-02-21 08:24 UTC, apalala-dev commented on packages/starknet_flutter/test/src/crypto/crypto_helper_test.dart
> +    // TODO the password must be 16 bytes long or it will fail
Good cath! It's an old comment, now that I've set up sha 256 it's not limited anymore 👍

2023-02-22 22:51 UTC, ptisserand requested changes

2023-02-22 22:51 UTC, ptisserand commented on packages/starknet/README.md
> +### Initial Setup
Initial setup need to be run in git repository top directory where [`pyproject.toml`](../../blob/main/pyproject.toml) is located

I suggest to add these commands in top directory README and refer this file here.

2023-02-22 22:51 UTC, ptisserand commented on packages/starknet/README.md
> +### Compile cairo contracts
Cairo contracts compilation command need to be run in  top directory where [`protostar.toml`](../../blob/main/protostar.toml) is located

I suggest to add these commands in top directory README and refer this file here.

2023-02-22 22:51 UTC, ptisserand commented on packages/starknet_flutter/lib/src/store/password_store.dart
> +    Uint8List? iv,
`iv` parameter is missing in `storeSecret` call

2023-02-23 09:23 UTC, ptisserand approved these changes

2023-02-23 09:24 UTC, merged