[WIP don't merge] Starknet get block
focustree/starknet.dart pull request #55
Opened 2022-08-04 19:06 UTC by erluxman

2022-08-18 12:46 UTC, gabsn requested changes
Hey Lux, good work, however a few points to fix before the merge:
- don't use relative or nested imports. Export your models from the `index.dart` instead
- don't use the `infuraGoerliRpc` endpoint. Instead use the `v010PathfinderGoerliTestnetUri` instead. It should have the `getBlockXXX` methods implemented.

2022-08-18 12:46 UTC, gabsn commented on lib/src/provider/read_provider.dart
> +import 'package:starknet/src/provider/model/get_block_txn_count.dart';
never import from deep nested path. You should add your file to the `exports` in the `index.dart`

2022-08-18 12:46 UTC, gabsn commented on lib/src/provider/read_provider.dart
> +import 'model/get_block_with_txs.dart';
don't use relative import, everything should be accessible from "package:starknet/starknet.dart"

2022-08-18 12:46 UTC, gabsn commented on test/provider/read_provider_test.dart
> +import 'package:starknet/src/provider/model/get_block_with_txs.dart';
don't use nested imports

2022-08-18 12:46 UTC, gabsn commented on test/provider/read_provider_test.dart
> +                  contains('method \'starknet_getBlockWithTxs\' not found'));
you should be able to use the v010 pathfinder provider for this test now and expect a real value

2022-08-24 17:29 UTC, erluxman commented
The tests are failing coz the server isn't available, please have a look at the tests.

2022-09-05 12:40 UTC, gabsn commented
@erluxman do you need help to have the tests pass?

2022-09-09 12:43 UTC, gabsn approved these changes
LGTM

2022-09-09 12:49 UTC, merged